### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by IamShubhamGupto** [dmar-bonn/neu-nbv#3]
Hello!

Could you share the IROS citation for this paper?

Thank you!
Shubham

**Comment by liren-jin** [comment]
Hi Shubham,

Thanks for reaching out.
The proceeding of IROS 2023 is still not out from IEEE. So I do not have the most correct citation atm. 
I updated my README regarding citation information (without DOI though). Or you can use the Arxiv version. 
As soon as I have the IROS citation, I will update the README again.

Cheers,
Liren
