### ISSUE TITLE
A question about the application of model

### ISSUE THREAD

**Issue by shenyehui** [dmar-bonn/neu-nbv#5]
Thank you for your work, may I ask if a new model needs to be re-trained for each new scenario？

**Comment by liren-jin** [comment]
Hi, thanks for reaching out!
I consider what you meant by "scenario" refers to different scenes in a dataset, e.g., there are around 100 scenes in DTU dataset. so for experiments on the same dataset, there is no need to retrain the model, since it can generalize to new scenes pretty well. However, if you want to try another dataset, it is recommended to do so, due to the domain shift. I provided two pre-trained models for DTU dataset and Shapenet dataset accordingly.

**Comment by shenyehui** [comment]
Hello, I studied your code and it looks like you sample and train all 100 scenes of DTU's dataset? I plan to extend to outdoor based on your method, the outdoor dataset I made also contains some scenes, should I sample and train for each scene?

**Comment by liren-jin** [comment]
we trained the DTU model on 88 scenes and tested it on 15 test scenes.
The training is pretty data-hungry I would say, especially for getting the reasonable aleatoric/data uncertainty. I am not sure what is the scale of your outdoor dataset.

**Comment by shenyehui** [comment]
Hi, the outdoor dataset I'm using is a common one used to train nerf, such as the Cambridge dataset.

**Comment by liren-jin** [comment]
not sure how feasible it is in this case. But maybe you can take the DTU pre-trained model and fine-tune it to the new dataset? For training you may need to create image pairs with varying overlap ratio as training examples and keep the remaining images for testing.

**Comment by shenyehui** [comment]
Thanks for the heads up, may I ask how the cameras.npz is made in your dataset? I open the scan1/cameras.npz file scale_mat_x all the same matrix?

**Comment by liren-jin** [comment]
DTU dataset follows exactly the same format as proposed in Pixelnerf. Please refer to scripts/neural_rendering/data 
And what is the issue of having same scale matrices?

**Comment by shenyehui** [comment]
Sorry for the confusion between scale_mat_x and world_mat_x, I will close this issue for now. thank you!

**Comment by shenyehui** [comment]
Sorry, I also have a question about render.
Is your method of rendering pixel colours different from Nerf, which takes the colour and opacity of each point on the ray and then accumulates them to get the colour of each pixel, whereas your method is to iterate through lstm to the last sampling point（Not using previous sampling points）, and then get the colour and uncertainty from the last get_features, mlp_feature and mlp_out. colour and uncertainty. Am I understanding this correctly?

**Comment by liren-jin** [comment]
correct! we use LSTM to mimic the sphere tracing process to speed up rendering. Only the surface points are considered for rendering. In case no surface points are found (features from reference views have large variance), the network should learn to output high uncertainty.

**Comment by shenyehui** [comment]
Dear author I have some details I don't understand, according to the paper feature after weighted_pooling the generated feature should be fmean,fvar, but look at this code feature after sampling the generated feature should be a fmean, not fvar? Is fmean and fvar combined into a feature, if so, then mlp_feature generated feature is also composed of fmean and fvar. Is it a combination of fmean and fvar, if so, then the feature generated by mlp_feature is also composed of fmean and fvar? Lastly I would like to ask if fmean,fvar are meant to be used by the lstm module? fmean and fvar end up going through mlp_out,as rgb logit mean and log variance respectively? what is the significance of fvar?

            feature, weight = self.mlp_feature(
                latent,
                p_feature,
            )  # (ON*RN*RB, d_feature)
            feature = util.weighted_pooling(
                feature, inner_dims=(self.num_ref_views, RB), weight=weight
            ).reshape(
                ON * RB, -1
            )  # (ON*RB, 2*d_feature)
            final_output = self.mlp_out(feature).reshape(ON, RB, -1)  # (ON, RB, d_out)

**Comment by liren-jin** [comment]
please have a look at the weighted_pooling function.

**Comment by shenyehui** [comment]
> please have a look at the weighted_pooling function.

I'm sorry for the trouble I've caused you by my negligence. One last question! Can I ask if fvar can be used as the uncertainty of fmean?

**Comment by liren-jin** [comment]
f_var and f_mean are statistics of features from reference images. we use a mlp to interpret these statistics into final mean and variance predictions. Theoretically, directly using f_var is doable, but the dimension does not fit.
