### ISSUE TITLE
Problem about OpenBLAS

### ISSUE THREAD

**Issue by YFish467** [dmar-bonn/neu-nbv#6]
Thank you for providing the source code and your training contributions. 
    Have you encountered any errors related to the OpenBLAS library during the process? Specifically, have you seen the following warning: 'OpenBLAS Warning: Detect OpenMP Loop, and this application may hang. Please rebuild the library with USE_OPENMP=1 option.' 
    Due to my limited experience, I'm unable to resolve this issue effectively. I only know that it occurred during the SanityCheck process. Could you please let me know if you've encountered a similar error or if you know how to resolve it?

**Comment by YFish467** [comment]
Although restricting the number of threads with OMP_NUM_THREADS=1 can avoid this error, it also reduces the training speed.

**Comment by liren-jin** [comment]
Hi thanks for the information. I do not encounter this error.
Could you please tell me where this error is triggered? Are you using GPU or CPU?

**Comment by YFish467** [comment]
I'm using GPU ,After executing the command `python train.py -M logs/dtu_training/checkpoints/best.ckpt --setup_cfg_path logs/dtu_training/training_setup.yaml` , here is the log message: 
[logs.txt](https://github.com/dmar-bonn/neu-nbv/files/15037913/logs.txt)
After displaying numerous warnings, the training can still commence normally, but the speed is very slow and it terminates unexpectedly

**Comment by liren-jin** [comment]
could you pls try different pytorch and torchvision version and let me know how it goes?

**Comment by YFish467** [comment]
Thank you for your advice. We have modified our environment according to the environment.yaml file, and now the training can proceed smoothly. Ultimately, it was an issue with the versions of PyTorch and TorchVision. Thanks again for your response.
