### ISSUE TITLE
in simulator

### ISSUE THREAD

**Issue by Dgf-3** [dmar-bonn/neu-nbv#7]
[debug.txt](https://github.com/user-attachments/files/15897717/debug.txt)

**Comment by liren-jin** [comment]
Hi, thanks for reaching out. It seems that you are not using nvidia gpu? This probably leads to the error messages in the log. Do you have dGPU from nvidia in your machine?

**Comment by Dgf-3** [comment]
Yes, I have an NVIDIA GPU on my machine, and I can see the GPU information normally using nvidia-smi in the container.

in the container:
(neu-nbv) root@60ad6a686d2a:/neu_nbv# glxinfo | grep OpenGL
libGL error: MESA-LOADER: failed to retrieve device information
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Unknown Intel Chipset
OpenGL version string: 1.3 Mesa 21.2.6
OpenGL extensions:

in the host terminal
jnu@jnu:/桌面$ glxinfo | grep OpenGL
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 520 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by liren-jin** [comment]
yes, but based on the log, opengl is not using your nvidia gpu.

**Comment by liren-jin** [comment]
maybe check this https://bbs.archlinux.org/viewtopic.php?id=260663

**Comment by Dgf-3** [comment]
Based on the hint that OpenGL was not utilizing the NVIDIA GPU, I executed the following commands to switch the active graphics card and successfully rebooted the system:

sudo prime-select nvidia
sudo reboot
After this, I was finally able to launch Gazebo through the container. It turns out that the issue was related to systems, especially laptops with hybrid graphics (dual graphics cards) configurations, where the system might default to using the integrated graphics card instead of the dedicated one. 
I am really grateful for your help.
